// Matcher: cxxRecordDecl(hasAttr(attr::Annotate, hasAnnotation("eos::peripheral")))
// En el callback, simplemente imprime el nombre de la clase.
#include "clang/AST/AST.h"
#include "clang/ASTMatchers/ASTMatchFinder.h"
#include "clang/Frontend/FrontendPluginRegistry.h"
#include <fstream>
#include <string>

using namespace clang;
using namespace clang::ast_matchers;

namespace {

class PeripheralHandler : public MatchFinder::MatchCallback {
public:
    void run(const MatchFinder::MatchResult &Result) override {
        auto *C = Result.Nodes.getNodeAs<CXXRecordDecl>("periph");
        if (!C || !C->hasDefinition()) return;

        std::string name = C->getNameAsString();
        std::ofstream out(name + "_gen.hpp");
        out << "// Auto-generated by EOSPlugin\n";
        out << "#pragma once\n\n";
        // Aquí generarías el código completo (enum, Shared, Services, etc.)
        // Este es solo un ejemplo mínimo:
        out << "class " << name << "Shared {\npublic:\n";
        for (auto *field : C->fields()) {
            for (auto *A : field->attrs()) {
                if (auto *ann = dyn_cast<AnnotateAttr>(A)) {
                    if (ann->getAnnotation() == "eos::shared") {
                        std::string f = field->getNameAsString();
                        out << "  decltype(" << f << ") get_" << f << "();\n";
                    }
                }
            }
        }
        out << "};\n";
    }
};

class EOSPluginAction : public PluginASTAction {
protected:
    std::unique_ptr<ASTConsumer> CreateASTConsumer(CompilerInstance &CI,
                                                   llvm::StringRef) override {
        auto Finder = std::make_unique<MatchFinder>();
        Finder->addMatcher(
            cxxRecordDecl(isExpansionInMainFile(),
                          hasAttr(attr::Annotate)).bind("periph"),
            &Handler
        );
        return Finder;
    }

    bool ParseArgs(const CompilerInstance &CI,
                   const std::vector<std::string> &args) override {
        return true;
    }

private:
    PeripheralHandler Handler;
};

} // namespace

static FrontendPluginRegistry::Add<EOSPluginAction>
X("eos-plugin", "Genera código para EOS Framework");
